name: 'Build'
description: 'Build CxxSwizzle test/samples'
inputs:
  buildType:
    required: false
    default: "Release"
  buildDir:
    required: true
  outputDir:
    required: true
  generator:
    required: true
  cc:
    description: 'C compiler'
    required: true
  cxx:
    description: 'C++ compiler'
    required: true
  triplet:
    description: "vcpkg triplet"
    required: true
  cxxFlags:
    description: "Additional C++ flags"
    required: false
  cmakeArgs:
    description: "Additional CMake arguments"
    required: false

runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set Environment vars
      run: |
        echo "CXX=${{ inputs.cxx }}" >> $GITHUB_ENV
        echo "CC=${{ inputs.cc }}"   >> $GITHUB_ENV
      shell: bash

    - name: Print Compiler Version
      if: runner.os != 'Windows'
      run: |
        ${{ inputs.cxx }} --version
      shell: bash

    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v6
      id: runvcpkg
      with:
        # Just install vcpkg for now, do not install any ports in this step yet.
        setupOnly: true
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: ${{ inputs.triplet }}

    - name: Build with CMake
      uses: lukka/run-cmake@v3
      id: runcmake
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        vcpkgTriplet: ${{ inputs.triplet }}
        useVcpkgToolchainFile: true
        buildDirectory: '${{ inputs.buildDir }}/'
        cmakeAppendedArgs: '-G "${{ inputs.generator }}" -DCMAKE_BUILD_TYPE=${{ inputs.buildType }} -DCMAKE_CXX_FLAGS="${{ inputs.cxxFlags }}" -DBUILD_SAMPLES=ON -DBUILD_SAMPLES_SIMD=ON -DBUILD_TESTS=ON ${{ inputs.cmakeArgs }}'
        buildWithCMakeArgs: '--config ${{ inputs.buildType }}'
    
    - name: Test with CTest
      shell: pwsh
      run: |
        cd ${{ inputs.buildDir }}/test
        ctest -V

    - name: Run samples
      shell: pwsh
      run: |
        cd ${{ inputs.outputDir }}
        ./sample_scalar_seascape -o sample_scalar_seascape.png
        ./sample_scalar_creation_by_silexars -o sample_creation_by_silexars.png
        ./sample_scalar_dry_ice_2 -n 100 -o sample_scalar_dry_ice_2.png
        ./sample_simd_vc_masked_seascape_patched -o sample_simd_vc_masked_seascape_patched.png
        ./sample_simd_vc_seascape_patched -o sample_simd_vc_seascape_patched.png
        ./sample_simd_vc_creation_by_silexars_patched -o sample_simd_vc_creation_by_silexars_patched.png

    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ${{ inputs.outputDir }}/sample_*.png
