name: 'Build'
description: 'Build CxxSwizzle test/samples'
inputs:
  buildType:
    required: false
    default: "Release"
  buildDir:
    required: true
  outputDir:
    required: true
  generator:
    required: true
  cc:
    description: 'C compiler'
    required: true
  cxx:
    description: 'C++ compiler'
    required: true
  triplet:
    description: "vcpkg triplet"
    required: true
  cxxFlags:
    description: "Additional C++ flags"
    required: false
  cmakeArgs:
    description: "Additional CMake arguments"
    required: false

runs:
  using: "composite"
  steps:
    - uses: lukka/get-cmake@latest
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set Environment vars
      run: |
        echo "CXX=${{ inputs.cxx }}" >> $GITHUB_ENV
        echo "CC=${{ inputs.cc }}"   >> $GITHUB_ENV
      shell: bash

    - name: Print Compiler Version
      if: runner.os != 'Windows'
      run: |
        ${{ inputs.cxx }} --version
      shell: bash

    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v11
      id: runvcpkg

    - name: Build with CMake
      uses: lukka/run-cmake@v10
      id: runcmake
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/cmakepresets/CMakeLists.txt'
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-multi-vcpkg'
        buildPresetAdditionalArgs: '[`--config Release`]'
    
    - name: Test with CTest
      shell: pwsh
      run: |
        cd ${{ inputs.buildDir }}/test
        ctest -V

    - name: Run samples
      shell: pwsh
      run: |
        cd ${{ inputs.outputDir }}

        echo sample_scalar__sh16c__doom
        ./sample_scalar__sh16c__doom -o sample_scalar__sh16c__doom.png -d 0.5 -n 15

        echo sample_scalar_seascape
        ./sample_scalar_seascape -o sample_scalar_seascape.png

        echo sample_scalar_creation_by_silexars
        ./sample_scalar_creation_by_silexars -o sample_creation_by_silexars.png -t 10

        echo sample_scalar_dry_ice_2
        ./sample_scalar_dry_ice_2 -n 25 -o sample_scalar_dry_ice_2.png -d 0.5

        echo sample_simd_vc_masked_seascape
        ./sample_simd_vc_masked_seascape -o sample_simd_vc_masked_seascape.png

        echo sample_simd_vc_seascape
        ./sample_simd_vc_seascape -o sample_simd_vc_seascape.png

        echo sample_simd_vc_creation_by_silexars
        ./sample_simd_vc_creation_by_silexars -o sample_simd_vc_creation_by_silexars.png -t 10

    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ${{ inputs.outputDir }}/sample_*.png
