name: no-parallelism-apple-clang
on: [push]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: clang++
          cc: clang
          triplet: x64-osx
          generator: Ninja
          buildDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}
          outputDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}/samples
          cmakeArgs: -DENABLE_PARALLELISM=OFF