name: clang-12
on: [push]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: clang++-12
          cc: clang-12
          triplet: x64-linux
          generator: Ninja
          buildDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}
          cmakeArgs: -DBUILD_SAMPLES=ON -DBUILD_SAMPLES_SIMD=ON -DBUILD_TESTS=ON

      - name: Run CTest
        run: |
         cd ${{ runner.workspace }}/b/${{ matrix.buildType }}/test
         ctest -V
