name: clang-11
on: [push]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: clang++-11
          cc: clang-11
          triplet: x64-linux
          generator: Ninja
          buildDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}
          outputDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}/samples
