name: g++10-tests
on: [push]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: g++
          cc: gcc
          triplet: x64-linux
          generator: Ninja
          buildDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}
          cmakeArgs: -DBUILD_SAMPLES=OFF -DBUILD_SAMPLES_SIMD=OFF -DBUILD_TESTS=ON
          cxxFlags: -march=native

      - name: Run CTest
        run: |
         cd ${{ runner.workspace }}/b/${{ matrix.buildType }}/test
         ctest -V
