name: CI
on: [push]

jobs:
  job:
    name: windows-Release
    runs-on: windows-latest
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - id: build
        uses: ./.github/actions/cmake-build
        with:
            cxx: cl.exe
            cc: cl.exe
            triplet: x64-windows
            generator: Visual Studio 16 2019
            cmakeArgs: -DBUILD_SAMPLES=ON
