name: vs2019-tests
on: [push]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: cl.exe
          cc: cl.exe
          triplet: x64-windows
          generator: Visual Studio 16 2019
          buildDir: ${{ runner.workspace }}/b/${{ matrix.buildType }}
          cmakeArgs: -DBUILD_SAMPLES=OFF -DBUILD_SAMPLES_SIMD=OFF -DBUILD_TESTS=ON

      - name: Run CTest
        run: |
         cd ${{ runner.workspace }}/b/${{ matrix.name }}/test
         ctest -V
