name: vs2019
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.buildType }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        buildType: [Release]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - id: build
        uses: ./.github/actions/cmake-build
        with:
          cxx: cl.exe
          cc: cl.exe
          triplet: x64-windows
          generator: Visual Studio 16 2019
          buildDir: ${{ runner.workspace }}/b
          outputDir: ${{ runner.workspace }}/b/samples/${{ matrix.buildType }}
